//Chelsea Fernandes
//app1, college.c

#include <assert.h>
#include <time.h>
#include <stdio.h>
#include <stdlib.h>
#include "app1.h"

int main()
{
	int id=0;
	int age=0;
	int randomage=0;
	int randomid=0;
	int maxnum=3000; //max number of people enrolled at the school
	int range=13;

	CLASS *sp = createDataSet(range, maxnum);

	srand(time(NULL));
	for(int i=0; i<1000; i++)//create 1000 students
	{
		age = rand()%13+18;
		randomid = rand()%2+1;

		if(i==0)//the first student to be inserted
		{
			id=randomid;
			insertion(sp, age, id);
			printf("%d: age: %d id: %d\n",(i+1), age, id);
		}
		else//every student after the first
		{

			id=id+randomid;//the id is the previous person's id +number generated by rand()
			insertion(sp, age, id);
			printf("%d: age: %d id: %d\n",(i+1), age, id);
		}
	}

	randomid=rand()%1999+1;//randomly generates student id (1-2000)
	randomage=rand()%12+18;

	printf("\nrandomly generated ID: %d\nrandomly generated age: %d\n",randomid, randomage);

	LIST *search = searchAge(sp, randomage);//returns whether there are students with the given age or not 
	/*
	if(search!=NULL)//a list of students with the same age is returned 
	{
		printf("Students with age of %d exist in set.\n", randomage);
	}
	else//there are no students with the given age 
	{
		printf("Students with the age of %d do not exist in the set.\n", randomage);
	}
	*/
	randomage=rand()%12+18;
	printf("\nrandomly generate age: %d\n", randomage);

	search = searchAge(sp, randomage); //determine if there are students with the randomly generated age
	
	if(search!=NULL)//if there are students in list with given age, delete
	{
		deletion(sp, search, randomage);//deletes all students with given age
	}
	else
	{
		printf("age with randomly generated age not found\n");
	}


	//randomly generat an ID, search for it in data set
	int agegap=0;
	agegap=maxAgeGap(sp);
	printf("Max age gap: %d\n", agegap);
	destroyDataSet(sp);
	return 0;
}
