//Chelsea Fernandes 
//app2, college.c

#include "app2.h"
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <time.h>
#include <stdio.h>

int main()
{
	int id=0;
	int age=0;
	//int randomint=0;
	int randomage=0;
	int randomid=0;
	int maxnum=3000; //max number of people enrolled at the school
	int range=13;
	
	createDataSet(maxnum);//creates the data structure 

	srand(time(NULL));
	for(int i=0; i<1000; i++)//randomly generates 1000 students and inserts into array
	{
		age = rand()%13+18;
		randomid = rand()%2+1;	
		if(i==0)//the first student to be inserted
		{
			id=randomid;
			insertion(age, id);
			printf("%d: age: %d id: %d\n",(i+1), age, id);
		}
		else//every student after the first
		{
			id=id+randomid;//the id is the previous person's id +number generated by rand()
			insertion(age, id);
			printf("%d: age: %d id: %d\n",(i+1), age, id);
		}
	}

	randomid=rand()%1999+1;//randomly generates a student id (1-2000)
	randomage=rand()%12+18;

	printf("\nrandomly generated ID: %d\nrandomly generated age: %d\n",randomid, randomage);
	int search = searchID(randomid);
	
	randomid=rand()%1999+1;
	printf("\nrandomly generated ID: %d\n", randomid);

	deletion(randomid);//deletes student with given id  if found 
	destroyDataSet();
	return 0;
}

